include:
  - board: nice_nano
    shield: tuball_right
    snippet: zmk-usb-logging
   
  - board: nice_nano
    shield: tuball_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging

  - board: nice_nano
    shield: settings_reset
 
